CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(32600) NOT NULL,
    password VARCHAR(32600) NOT NULL,
    role VARCHAR(16) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE UNIQUE INDEX uq_users_email_normalized
    ON users (lower(btrim(email)));

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort_order SMALLINT NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uc_categories_code UNIQUE (code),
    CONSTRAINT uc_categories_name UNIQUE (name)
);
