ALTER TABLE projects
    ADD external_id UUID;

ALTER TABLE projects
    ALTER COLUMN external_id SET NOT NULL;

DROP SEQUENCE categories_seq CASCADE;

DROP SEQUENCE users_seq CASCADE;

ALTER TABLE projects
    DROP COLUMN id;

ALTER TABLE projects
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

CREATE SEQUENCE IF NOT EXISTS projects_id_seq;
ALTER TABLE projects
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE projects
    ALTER COLUMN id SET DEFAULT nextval('projects_id_seq');

ALTER SEQUENCE projects_id_seq OWNED BY projects.id;

ALTER TABLE projects
    ALTER COLUMN published_at DROP NOT NULL;

ALTER TABLE projects
    ALTER COLUMN withdrawn_at DROP NOT NULL;