CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id UUID NOT NULL,
    author_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    current_submission_no INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(255) NOT NULL,
    published_at TIMESTAMP(6) WITHOUT TIME ZONE,
    withdrawn_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_author
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_projects_professor
        FOREIGN KEY (professor_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_projects_author UNIQUE (id, author_id),
    CONSTRAINT uq_projects_professor UNIQUE (id, professor_id)
);
