CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    sort_order SMALLINT                                NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id           UUID                                    NOT NULL,
    author_id             BIGINT                                  NOT NULL,
    professor_id          BIGINT                                  NOT NULL,
    current_submission_no INTEGER                                 NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    published_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    withdrawn_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    version               INTEGER                                 NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id UUID                                    NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    email       VARCHAR(32600)                          NOT NULL,
    password    VARCHAR(32600)                          NOT NULL,
    role        VARCHAR(16)                             NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_code UNIQUE (code);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_PROFESSOR FOREIGN KEY (professor_id) REFERENCES users (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);


