CREATE TABLE project_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT NOT NULL,
    submission_no INTEGER NOT NULL,
    name VARCHAR(150) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT pk_project_participants PRIMARY KEY (id),
    CONSTRAINT fk_participants_submission
        FOREIGN KEY (project_id, submission_no)
        REFERENCES project_submissions (project_id, submission_no)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_participants_position
        UNIQUE (project_id, submission_no, position),
    CONSTRAINT ck_participants_position
        CHECK (position BETWEEN 1 AND 10)
);

CREATE TABLE project_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT NOT NULL,
    submission_no INTEGER NOT NULL,
    professor_id BIGINT NOT NULL,
    decision VARCHAR(16) NOT NULL,
    comment TEXT,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_project_reviews PRIMARY KEY (id),
    CONSTRAINT fk_reviews_submission
        FOREIGN KEY (project_id, submission_no)
        REFERENCES project_submissions (project_id, submission_no)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_reviews_professor_user
        FOREIGN KEY (professor_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_reviews_assigned_professor
        FOREIGN KEY (project_id, professor_id)
        REFERENCES projects (id, professor_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_reviews_submission UNIQUE (project_id, submission_no)
);

CREATE TABLE project_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT NOT NULL,
    submission_no INTEGER NOT NULL,
    actor_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    from_status VARCHAR(16),
    to_status VARCHAR(16) NOT NULL,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_project_events PRIMARY KEY (id),
    CONSTRAINT fk_events_submission
        FOREIGN KEY (project_id, submission_no)
        REFERENCES project_submissions (project_id, submission_no)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_events_actor_user
        FOREIGN KEY (actor_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_events_author
        FOREIGN KEY (project_id, actor_id)
        REFERENCES projects (id, author_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_events_type
        UNIQUE (project_id, submission_no, event_type),
    CONSTRAINT ck_events_transition CHECK ((
        (
            event_type = 'SUBMITTED'
            AND submission_no = 1
            AND from_status IS NULL
            AND to_status = 'PENDING'
        )
        OR (
            event_type = 'RESUBMITTED'
            AND submission_no > 1
            AND from_status = 'REJECTED'
            AND to_status = 'PENDING'
        )
        OR (
            event_type = 'EDITED_AFTER_APPROVAL'
            AND submission_no > 1
            AND from_status = 'APPROVED'
            AND to_status = 'PENDING'
        )
        OR (
            event_type = 'WITHDRAWN'
            AND from_status = 'APPROVED'
            AND to_status = 'APPROVED'
        )
    ) IS TRUE)
);
